wandb_version: 1

epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 32
num_atoms:
  desc: null
  value: 10
num_embeddings:
  desc: null
  value: 128
cutoff_disc:
  desc: null
  value: 5.0
criterion:
  desc: null
  value: MSELoss
Optimizer:
  desc: null
  value: Adam0001
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700912448.061449
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
